spring:
  datasource:
    url: "jdbc:h2:mem:testdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;"

logging:
  level:
    root: INFO
    de.lathspell: DEBUG
    org.springframework: INFO
    org.springframework.jdbc.core: TRACE # Parameters via o.s.jdbc.core.StatementCreatorUtils
    org.springframework.jdbc.core.JdbcTemplate: DEBUG # SQL Queries
    # There is no Hibernate involved!
