create table authors (
    id bigint generated by default as identity primary key,
    name text not null
);
create index on authors(name);

create table books (
    id bigint  generated by default as identity primary key,
    title text not null,
    author_id bigint not null
);
create index on books(title);
create index on books(author_id);
